services:
  - type: web
    name: business-tracker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: business-tracker-db
          property: connectionString

databases:
  - name: business-tracker-db
    plan: free
    ipAllowList: [] 