services:
  - type: web
    name: business-tracker
    env: node
    buildCommand: npm install; npm run build
    startCommand: npm run start
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromEnvFile: .env
      - key: VITE_SUPABASE_URL
        fromEnvFile: .env
      - key: VITE_SUPABASE_ANON_KEY
        fromEnvFile: .env